name: Bundle with PyInstaller
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -U pyinstaller
      - name: Build and compile the program
        run: |
          pyinstaller --windowed main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: Analizatorius-PyInstaller
            path: dist/main/
