name: Compile with Nuitka 32-bit (legacy experimental, not recommended)
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.10
          architecture: 'x86'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements32.txt
          python -m pip install nuitka==1.3.1
      - name: Compile the program
        run: >
          python
          -m nuitka
          --assume-yes-for-downloads
          --enable-plugin=pyside2
          --include-qt-plugins=sensible,styles
          --nofollow-import-to=scipy
          --nofollow-import-to=PySide2.QtNetwork
          --nofollow-import-to=PySide2.QtQml
          --nofollow-import-to=tkinter
          --include-module=matplotlib.backends.backend_pdf
          --include-module=matplotlib.backends.backend_qtagg
          --windows-icon-from-ico=icon.ico
          --windows-disable-console
          --standalone
          analyser\main.py
      - name: Copy data files
        run: |
          xcopy analyser\data main.dist\data /E /H /I /Y
          xcopy analyser\icon.png main.dist\icon.png* /Y
      - name: Create a NSIS script
        run: |
          python generate-nsis.py main.dist Install-Analizatorius-Nuitka32.exe
      - name: Create an installer
        uses: joncloud/makensis-action@v3.6
        with:
          script-file: "install-script.nsi"
          arguments: "/V3"
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
            name: Mokinių pasiekimų ir lankomumo stebėsenos sistema
            path: Install-Analizatorius-Nuitka32.exe
            
